package ejer1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;

/**
 *
 * @author cla
 */
public class VentanaOperaciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaOperaciones.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public VentanaOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelResultado1 = new javax.swing.JPanel();
        labelNumUno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelResultadoTxt = new javax.swing.JLabel();
        textoPrimerNum = new javax.swing.JTextField();
        textoSegundoNum = new javax.swing.JTextField();
        botonSumar = new javax.swing.JButton();
        botonRestar = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelResultado1.setToolTipText("");

        labelNumUno.setText("Primer Numero");

        jLabel2.setText("Segundo Numero");

        labelResultadoTxt.setText("Resultado: ");

        textoPrimerNum.addActionListener(this::textoPrimerNumActionPerformed);

        textoSegundoNum.addActionListener(this::textoSegundoNumActionPerformed);

        botonSumar.setText("Sumar");
        botonSumar.addActionListener(this::botonSumarActionPerformed);

        botonRestar.setText("Restar");
        botonRestar.addActionListener(this::botonRestarActionPerformed);

        botonMultiplicar.setText("Multiplicar");
        botonMultiplicar.addActionListener(this::botonMultiplicarActionPerformed);

        botonDividir.setText("Dividir");
        botonDividir.addActionListener(this::botonDividirActionPerformed);

        labelResultado.setText("0");

        javax.swing.GroupLayout labelResultado1Layout = new javax.swing.GroupLayout(labelResultado1);
        labelResultado1.setLayout(labelResultado1Layout);
        labelResultado1Layout.setHorizontalGroup(
            labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelResultado1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labelResultado1Layout.createSequentialGroup()
                        .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumUno)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoSegundoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoPrimerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(labelResultado1Layout.createSequentialGroup()
                        .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, labelResultado1Layout.createSequentialGroup()
                                .addComponent(labelResultadoTxt)
                                .addGap(18, 18, 18)
                                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, labelResultado1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonSumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(labelResultado1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonRestar)
                                    .addComponent(botonDividir))
                                .addGap(65, 65, 65))
                            .addGroup(labelResultado1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        labelResultado1Layout.setVerticalGroup(
            labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelResultado1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumUno)
                    .addComponent(textoPrimerNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoSegundoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResultadoTxt)
                    .addComponent(jLabel1)
                    .addComponent(labelResultado))
                .addGap(36, 36, 36)
                .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSumar)
                    .addComponent(botonRestar))
                .addGap(18, 18, 18)
                .addGroup(labelResultado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMultiplicar)
                    .addComponent(botonDividir))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        botonSumar.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDividirActionPerformed
        try {
            double numUno = Double.parseDouble(textoPrimerNum.getText());
            double numDos = Double.parseDouble(textoSegundoNum.getText());

            double resultadoDivision = LogicaOperaciones.dividir(numUno, numDos);
            labelResultado.setText("" + resultadoDivision);

        }catch(FormatoInvalido e){
            labelResultado.setText("Error.");
            JOptionPane.showMessageDialog(this, "No se puede dividir para cero.", "Division para cero",JOptionPane.ERROR_MESSAGE);
        }catch (NumberFormatException n){
            labelResultado.setText("Error.");
            JOptionPane.showMessageDialog(this, "Porfavor ingrese solo numeros.", "Ingreso de datos invalido",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonDividirActionPerformed

    private void botonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicarActionPerformed
        try {
            double numUno = Double.parseDouble(textoPrimerNum.getText());
            double numDos = Double.parseDouble(textoSegundoNum.getText());

            double resultadoMultiplicacion = LogicaOperaciones.multiplicar(numUno, numDos);
            labelResultado.setText("" + resultadoMultiplicacion);
        }catch (NumberFormatException n){
            labelResultado.setText("Error.");
            JOptionPane.showMessageDialog(this, "Porfavor ingrese solo numeros.", "Ingreso de datos invalido",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonMultiplicarActionPerformed

    private void botonRestarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            double numUno = Double.parseDouble(textoPrimerNum.getText());
            double numDos = Double.parseDouble(textoSegundoNum.getText());

            double resultadoResta = LogicaOperaciones.restar(numUno, numDos);

            labelResultado.setText("" + resultadoResta);
        }catch (NumberFormatException n){
            labelResultado.setText("Error.");
            JOptionPane.showMessageDialog(this, "Porfavor ingrese solo numeros.", "Ingreso de datos invalido",JOptionPane.ERROR_MESSAGE);
        }
    }                                           

    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        try{
            double primerNum = Double.parseDouble(textoPrimerNum.getText());//necesitamos convertir lo que nos de el usuario en un double, que no viene por defecto
            double segundoNum = Double.parseDouble(textoSegundoNum.getText()); //pero antes necesitamos obtener el texto que ingreso

            double resultadoSuma = LogicaOperaciones.sumar(primerNum, segundoNum);//llamamos al metodo de suma en la clase LogicaOperaciones

            labelResultado.setText("" + resultadoSuma);

        }catch (NumberFormatException n){
            labelResultado.setText("Error.");
            JOptionPane.showMessageDialog(this, "Porfavor ingrese solo numeros.", "Ingreso de datos invalido",JOptionPane.ERROR_MESSAGE);//mensaje de error
        }
    }//GEN-LAST:event_botonSumarActionPerformed

    private void textoSegundoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSegundoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSegundoNumActionPerformed

    private void textoPrimerNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPrimerNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPrimerNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaOperaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonRestar;
    private javax.swing.JButton botonSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNumUno;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JPanel labelResultado1;
    private javax.swing.JLabel labelResultadoTxt;
    private javax.swing.JTextField textoPrimerNum;
    private javax.swing.JTextField textoSegundoNum;
    // End of variables declaration//GEN-END:variables
}
