/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejer2;

import javax.swing.*;

/**
 *
 * @author cla
 */
public class Encuesta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Encuesta.class.getName());

    /**
     * Creates new form Encuesta
     */
    public Encuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jFrame1 = new javax.swing.JFrame();
        pregunta1 = new javax.swing.ButtonGroup();
        pregunta2 = new javax.swing.ButtonGroup();
        pregunta3 = new javax.swing.ButtonGroup();
        labelP1 = new javax.swing.JLabel();
        opc2P1 = new javax.swing.JRadioButton();
        opc1P1 = new javax.swing.JRadioButton();
        opc3P1 = new javax.swing.JRadioButton();
        labelP2 = new javax.swing.JLabel();
        opc2P2 = new javax.swing.JRadioButton();
        opc1P2 = new javax.swing.JRadioButton();
        opc3P2 = new javax.swing.JRadioButton();
        labelP3 = new javax.swing.JLabel();
        opc2P3 = new javax.swing.JRadioButton();
        opc1P3 = new javax.swing.JRadioButton();
        opc3P3 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        labelEncuesta = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


        labelP1.setText("Pregunta 1. Cual de las siguientes materias prefieres?\n");

        pregunta1.add(opc2P1);
        opc2P1.setText("POO");

        pregunta1.add(opc1P1);
        opc1P1.setText("Redes");

        pregunta1.add(opc3P1);
        opc3P1.setText("Fisica");

        labelP2.setText("Pregunta 2. Que tan frecuentemente entiendes los temas tratados en clase?\n");

        pregunta2.add(opc2P2);
        opc2P2.setText("Muy frecuentemente");

        pregunta2.add(opc1P2);
        opc1P2.setText("Frecuentemente");

        pregunta2.add(opc3P2);
        opc3P2.setText("Rara vez");

        labelP3.setText("Pregunta 3. Cuantas horas sueles dedicar para desarrollar las tareas por materia?\n");

        pregunta3.add(opc2P3);
        opc2P3.setText("1-3");

        pregunta3.add(opc1P3);
        opc1P3.setText("3-5");

        pregunta3.add(opc3P3);
        opc3P3.setText("5-7");

        labelEncuesta.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelEncuesta.setText("Encuesta");

        btnEnviar.setBackground(java.awt.Color.lightGray);
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(labelEncuesta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opc3P1)
                                    .addComponent(opc1P1)
                                    .addComponent(opc2P1)
                                    .addComponent(labelP1)
                                    .addComponent(opc3P2)
                                    .addComponent(opc1P2)
                                    .addComponent(opc2P2)
                                    .addComponent(labelP2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opc3P3)
                            .addComponent(opc1P3)
                            .addComponent(opc2P3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelP3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnEnviar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelEncuesta)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelP1)
                .addGap(30, 30, 30)
                .addComponent(opc1P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opc2P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opc3P1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelP2)
                .addGap(18, 18, 18)
                .addComponent(opc1P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opc2P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opc3P2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelP3)
                .addGap(18, 18, 18)
                .addComponent(opc1P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opc2P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opc3P3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        String resultadoP1 = null;
        String resultadoP2 = null;
        String resultadoP3 = null;

        if (opc1P1.isSelected()) resultadoP1 = opc1P1.getText();
        else if (opc2P1.isSelected()) resultadoP1 = opc2P1.getText();
        else if (opc3P1.isSelected()) resultadoP1 = opc3P1.getText();

        if (opc1P2.isSelected()) resultadoP2 = opc1P2.getText();
        else if (opc2P2.isSelected()) resultadoP2 = opc2P2.getText();
        else if (opc3P2.isSelected()) resultadoP2 = opc2P3.getText();

        if (opc1P3.isSelected()) resultadoP3 = opc2P1.getText();
        else if (opc2P3.isSelected()) resultadoP3 = opc2P3.getText();
        else if (opc3P3.isSelected()) resultadoP3 = opc3P3.getText();

        if (resultadoP1 == null || resultadoP2 == null || resultadoP3 == null){
            JOptionPane.showMessageDialog(this, "Opcion no ingresada", "Error", JOptionPane.ERROR_MESSAGE);
        }else mostrarMensaje(resultadoP1, resultadoP2, resultadoP3);

        pregunta1.clearSelection();//limpia la encuesta
        pregunta2.clearSelection();
        pregunta3.clearSelection();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void mostrarMensaje(String resultadoP1, String resultadoP2, String resultadoP3){
        JOptionPane.showMessageDialog(this, "Resultados:\n" +
                "Pregunta 1: " + resultadoP1 +
                "\nPregunta 2: " + resultadoP2 +
                "\nPregunta 3: " + resultadoP1 );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Encuesta().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelEncuesta;
    private javax.swing.JLabel labelP1;
    private javax.swing.JLabel labelP2;
    private javax.swing.JLabel labelP3;
    private javax.swing.JRadioButton opc1P1;
    private javax.swing.JRadioButton opc1P2;
    private javax.swing.JRadioButton opc1P3;
    private javax.swing.JRadioButton opc2P1;
    private javax.swing.JRadioButton opc2P2;
    private javax.swing.JRadioButton opc2P3;
    private javax.swing.JRadioButton opc3P1;
    private javax.swing.JRadioButton opc3P2;
    private javax.swing.JRadioButton opc3P3;
    private javax.swing.ButtonGroup pregunta1;
    private javax.swing.ButtonGroup pregunta2;
    private javax.swing.ButtonGroup pregunta3;
    // End of variables declaration//GEN-END:variables
}
